name: Rust CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy

      - name: Run tests
        run: cargo test

      - name: Run clippy
        run: cargo clippy -- -D warnings
